export const STRING = {
    SAYLANI: "Saylani",
    SAHULAT: "Sahulat",
    LOGIN: "Login",
    REGISTER: "Register",
    REGISTER_NOW: "Register Now",
    SHAPPING_FINANCIAL: "Shaping Financial",
    FUTURES: "Futures",
    WITH_CARE: "with Care",
    HERO_PERA: "Interest-free loans to empower your dreams. Join thousands of families building a better tomorrow with Saylani Sahulat.",
    GET_STARTED_BUTTON: "Get Started",
    INTERESTE_RATE: "Interest Rate",
    MAX_LOAN: "Max Loan",
    LOAN_SCHEMES: "Our Loan Schemes",
    TAILORED: "Tailored",
    FINANCIAL_SOL: "Financial Solutions",
    FOR_EVERY: "for Every Need",
    CATEGORY_PERA: "Saylani Welfare provides interest-free loans across various categories to help you achieve your goals without any financial burden.",
    APPLY_NOW: "Apply Now",
    LOAN_CALCULATOR: "Loan Calculator",
    CALCULATOR_PLAN: "Plan your financial journey with zero interest",
    CUSTOMIZE_LOAN: "Customize Your Loan",
    SELECT_CATEGORIES: "Select Category",
    WEDDING_LOANS: "Wedding Loans",
    HOME_LOANS: "Home Construction",
    BUSINESS_LOANS: "Business Startup",
    EDUCATIONS_LOANS: "Education Loans",
    LOAN_AMOUNT: "Loan Amount",
    PKR: 'PKR',
    DEPOSIT: "Deposit",
    YEARS: "Years",
    ESTIMATED_RES: "Estimated Result",
    MONTHLY_INST: "Monthly Installment",
    LOAN_TYPE: "Loan Type:",
    TOTAL_DURATION: "Total Duration",
    UPFRONT_DEPOSIT: "Upfront Deposit",
    PROCEED_BTN: "Proceed",
    INSTRUCTION: '*Calculations are based on 0% interest rate policy.',
    TRUST_YEAR: "Years of Trust",
    ABOUT_SAYLANI: "About Saylani Sahulat",
    WE_PROVIDE: "We provide more than",
    JUST_LOAN: 'just a loan.',
    ABOUT_PARA: "Saylani Welfare International Trust has been working for decades to eradicate poverty. With Saylani Sahulat, we are digitizing the spirit of Qarz-e-Hasana, making it easier for every Pakistani to build their future with dignity.",
    FOOTER_RESERVED: "© 2026 Qarz-e-Hasana Program. All rights reserved.",
    DEVELOPED_BY: "Developed by",
    NAVEED_AHMED: "NAVEED AHMED",
    CREATE_ACCOUNT: "Create Account",
    REG_SUBTITLE: "Enter details to get your temporary password",
    CNIC_NUM: "CNIC Number",
    FULL_NAME: "Full Name",
    EMAIL_ADD: "Email Address",
    PROCESSING_LOAD: "Processing...",
    ALREADY_HAVE_AN: "Already have an account?",
    LOGIN_HERE: "Login here",
    WELCOME_BACK: "Welcome Back",
    LOGIN_SUBTITILE: "Log in with your registered email and password",
    LOGIN_BTN: "Securing Session...",
    SIGN_IN: "Sign In",
    NOT_REG_YET: "Not registered yet?",
    CREATE_AN_AC: " Create an account",
    SET_NEW_PASS: "Set New Password",
    NEW_PASS_SUBTITLE: "Your security is our priority. Please update your temporary password to continue.",
    TEMP_PASS: "Temporary Password",
    NEW_SEC_PASS: "New Secure Password",
    CONF_NEW_PASS: "Confirm New Password",
    UPDATING: "Updating...",
    SEC_MY_AC: "Secure My Account",
    
}